### ISSUE TITLE
All uploaded IPA files are invalid

### ISSUE THREAD

**Issue by xml520** [simonnilsson/ios-uploader#18]
After many tests, IPA uploaded with this tool indicates that IPA is invalid, while other official uploads have no problem

**Comment by simonnilsson** [comment]
Hi @xml520. Are you saying that Apple says it is invalid after the upload is completed or are you getting that as an error from ios-uploader? Can you post the exact error you are getting?

**Comment by ABD2k** [comment]
Hello. I think the same thing happens to me, ios-uploader fulfills its function but minutes later I receive an email saying: 
ITMS-90161: Invalid Provisioning Profile - The provisioning profile included in the bundle com.ghostsoft.acceso [Payload/**Proyect**] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal.

> Hola @xml520. ¿Está diciendo que Apple dice que no es válido después de que se complete la carga o lo está recibiendo como un error de ios-uploader? ¿Puede publicar el error exacto que está recibiendo?

**Comment by simonnilsson** [comment]
Hi @ABD2k , thanks for the additional information on this issue. 

So this looks like an issue with code signing when the .ipa file was built. I'm guessing a Development Provisioning profile was used instead of a Distribution Provisioning profile. How you configure and set this up depends on the platform used to build the app (Xcode, Xamarin, Expo, e.t.c.) and is outside the scope of this tool. 

ios-uploader does not validate this before uploading, hence why the error is received from App Store post upload.

See this question on Stack Overflow for more information: https://stackoverflow.com/questions/28960751/error-code-90161-invalid-provisioning-profile

**Comment by simonnilsson** [comment]
Closing this issue as this most likely is not a problem with ios-uploader. ios-iploader makes no modifications to the actual IPA.
